apiVersion: v1
kind: Secret
metadata:
  name: inventro-registry
  namespace: kube-system
  annotations:
    digitalocean.com/dosecret-identifier: inventro-registry
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: insert_base64_encoded_docker_config_here