apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: inventro
resources:
  - namespace.yaml
  - secrets/do-spaces-secret.yaml
  - secrets/docker-reg.yaml
  - secrets/django-secret.yaml
  - secrets/postgres-secret.yaml
  - secrets/url-secret.yaml
  - config/config.yaml
  - services/postgres-svc.yaml
  - deployments/postgres-deployment.yaml
  - services/web-svc.yaml
  - deployments/web-deployment.yaml
  - cronjob-backup.yaml
  - hpa.yaml
  - claim.yaml
